import React, { useState } from \"react\";
import {\n    Dialog,\n    DialogContent,\n    DialogDescription,\n    DialogFooter,\n    DialogHeader,\n    DialogTitle,\n    DialogTrigger,\n} from \"@/components/ui/dialog\";
import { Button } from \"@/components/ui/button\";
import { Input } from \"@/components/ui/input\";
import { Label } from \"@/components/ui/label\";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from \"@/components/ui/select\";
import { BellPlus } from \"lucide-react\";

export default function NewAlertDialog({ ticker }) {\n    const [isOpen, setIsOpen] = useState(false);\n\n    return (\n        <Dialog open={isOpen} onOpenChange={setIsOpen}>\n            <DialogTrigger asChild>\n                <Button size=\"sm\" className=\"h-8 text-xs gap-1.5\">\n                    <BellPlus className=\"w-3.5 h-3.5\" /> Set Alert\n                </Button>\n            </DialogTrigger>\n            <DialogContent className=\"sm:max-w-[425px]\">\n                <DialogHeader>\n                    <DialogTitle>Set Price Alert</DialogTitle>\n                    <DialogDescription>\n                        We'll notify you when {ticker || \"the asset\"} hits your target price.\n                    </DialogDescription>\n                </DialogHeader>\n                <div className=\"grid gap-4 py-4\">\n                    <div className=\"grid grid-cols-4 items-center gap-4\">\n                        <Label htmlFor=\"ticker\" className=\"text-right\">Asset</Label>\n                        <Input id=\"ticker\" defaultValue={ticker || \"AAPL\"} className=\"col-span-3\" />\n                    </div>\n                    <div className=\"grid grid-cols-4 items-center gap-4\">\n                        <Label htmlFor=\"condition\" className=\"text-right\">Condition</Label>\n                        <Select defaultValue=\"above\">\n                            <SelectTrigger className=\"col-span-3\">\n                                <SelectValue />\n                            </SelectTrigger>\n                            <SelectContent>\n                                <SelectItem value=\"above\">Price Above</SelectItem>\n                                <SelectItem value=\"below\">Price Below</SelectItem>\n                                <SelectItem value=\"percent\">% Change Today</SelectItem>\n                            </SelectContent>\n                        </Select>\n                    </div>\n                    <div className=\"grid grid-cols-4 items-center gap-4\">\n                        <Label htmlFor=\"target\" className=\"text-right\">Target</Label>\n                        <Input id=\"target\" type=\"number\" placeholder=\"0.00\" className=\"col-span-3\" />\n                    </div>\n                </div>\n                <DialogFooter>\n                    <Button type=\"submit\" onClick={() => setIsOpen(false)}>Create Alert</Button>\n                </DialogFooter>\n            </DialogContent>\n        </Dialog>\n    );\n}
