import React from \"react\";
import { useLocation, useNavigate } from \"react-router-dom\";
import { Search, Bell, User, Menu, ChevronLeft } from \"lucide-react\";
import { Input } from \"@/components/ui/input\";
import { Button } from \"@/components/ui/button\";
import UserProfileSheet from \"@/components/user/UserProfileSheet\";
import { useMobile } from \"@/hooks/use-mobile\";

export default function TopBar() {\n    const location = useLocation();\n    const navigate = useNavigate();\n    const isMobile = useMobile();\n\n    const getPageTitle = () => {\n        const path = location.pathname.substring(1);\n        if (!path) return \"Dashboard\";\n        if (path.startsWith(\"asset/\")) return \"Asset Analysis\";\n        return path.charAt(0).toUpperCase() + path.slice(1);\n    };\n\n    const isAssetPage = location.pathname.startsWith(\"/asset/\");\n\n    return (\n        <header className=\"h-16 border-b border-border/50 bg-background/80 backdrop-blur-md px-4 md:px-8 flex items-center justify-between sticky top-0 z-30\">\n            <div className=\"flex items-center gap-4\">\n                {isAssetPage && (\n                    <Button \n                        variant=\"ghost\" \n                        size=\"icon\" \n                        className=\"h-8 w-8 rounded-full\"\n                        onClick={() => navigate(-1)}\n                    >\n                        <ChevronLeft className=\"w-5 h-5\" />\n                    </Button>\n                )}\n                <h2 className=\"font-bold text-lg hidden sm:block\">{getPageTitle()}</h2>\n            </div>\n\n            {/* Search Bar - hidden on mobile, replaced by icon */}\n            <div className=\"flex-1 max-w-xl mx-8 hidden md:block\">\n                <div className=\"relative group\">\n                    <Search className=\"absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground group-focus-within:text-primary transition-colors\" />\n                    <Input \n                        placeholder=\"Search markets, stocks, crypto...\" \n                        className=\"bg-accent/30 border-none pl-10 h-10 w-full focus-visible:ring-1 focus-visible:ring-primary/30\"\n                    />\n                </div>\n            </div>\n\n            <div className=\"flex items-center gap-2 md:gap-4\">\n                <Button variant=\"ghost\" size=\"icon\" className=\"md:hidden\">\n                    <Search className=\"w-5 h-5 text-muted-foreground\" />\n                </Button>\n                \n                <Button variant=\"ghost\" size=\"icon\" className=\"relative\">\n                    <Bell className=\"w-5 h-5 text-muted-foreground\" />\n                    <span className=\"absolute top-2 right-2.5 w-2 h-2 bg-primary rounded-full border-2 border-background\"></span>\n                </Button>\n\n                <div className=\"h-8 w-[1px] bg-border mx-1 hidden sm:block\" />\n\n                <UserProfileSheet>\n                    <Button variant=\"ghost\" size=\"icon\" className=\"rounded-full bg-accent/40\">\n                        <User className=\"w-5 h-5 text-foreground\" />\n                    </Button>\n                </UserProfileSheet>\n            </div>\n        </header>\n    );\n}
